---
title: AEL04
subtitle: Listing of Patient Deaths
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

::: panel-tabset
## Data Setup

```{r setup, message = FALSE}
#| code-fold: show

library(dplyr)
library(rlistings)

adsl <- random.cdisc.data::cadsl

out <- adsl %>%
  filter(!is.na(DTHADY)) %>%
  mutate(
    ID = paste(SITEID, SUBJID, sep = "/"),
    AGSXRC = paste(AGE, SEX, RACE, sep = "/"),
    TRTSD = toupper(format(as.Date(TRTSDTM), "%d%b%Y"))
  ) %>%
  arrange(SUBJID) %>%
  select(ID, AGSXRC, TRT01A, TRTSD, EOSDY, DTHADY, DTHCAUS, ADTHAUT)

var_labels(out) <- c(
  ID = "Center/Patient ID",
  AGSXRC = "Age/Sex/Race",
  TRT01A = "Treatment",
  TRTSD = "Date of First\nStudy Drug\nAdministration",
  EOSDY = "Day of Last\nStudy Drug\nAdministration",
  DTHADY = "Day of\nDeath",
  DTHCAUS = "Cause of Death",
  ADTHAUT = "Autopsy\nPerformed?"
)
```

## Standard Listing

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("TRT01A", "ID"),
  disp_cols = names(out),
  main_title = "Listing of Patient Deaths"
)

head(lsting, 20)
```

`r webr_code_labels <- c("setup", "lsting")` {{< include ../../_utils/webr.qmd >}}
:::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}
:::
