---
title: PKCG03
subtitle: Plot of Mean PK Concentration Over Time by Cohort
---

------------------------------------------------------------------------

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(tern)
library(scda)
library(dplyr)
library(ggplot2)
library(nestcolor)

adsl_f <- synthetic_cdisc_dataset("latest", "adsl") %>%
  filter(SAFFL == "Y" & ARM != "B: Placebo") %>%
  df_explicit_na()

adpc <- synthetic_cdisc_dataset("latest", "adpc") %>%
  mutate(Patient_ID = sub(".*id-", "", USUBJID)) %>%
  filter(PARAM == "Plasma Drug X") %>%
  droplevels() %>%
  df_explicit_na()
```

## Plot in Linear Scale

```{r}
use_title <- "Plot of Mean (+/- SD) Plasma Concentrations Over Time by Treatment, \nPK Evaluable Patients"
use_subtitle <- "Analyte:"
use_footnote <- "Program: \nOutput:"

result <- g_lineplot(
  df = adpc,
  variables = control_lineplot_vars(
    x = "NRELTM1",
    y = "AVAL",
    strata = "ARM",
    paramcd = "PARAM",
    y_unit = "AVALU"
  ),
  alt_counts_df = adsl_f,
  y_lab = "Concentration",
  y_lab_add_paramcd = FALSE,
  y_lab_add_unit = TRUE,
  interval = "mean_sdi",
  whiskers = c("mean_sdi_lwr", "mean_sdi_upr"),
  title = use_title,
  subtitle = use_subtitle,
  caption = use_footnote,
  ggtheme = theme_nest()
)

result + theme(plot.caption = element_text(hjust = 0))
```

## Plot in Log Scale

```{r, warning=FALSE}
use_title <- "Plot of Mean (+/- SD) Log-Scale Plasma Concentrations Over Time by Treatment, \nPK Evaluable Patients"
use_subtitle <- "Analyte:"
use_footnote <- "Program: \nOutput:"

adpc <- adpc %>%
  mutate(avalog = ifelse(AVAL != 0, AVAL, 0.001))

result <- g_lineplot(
  df = adpc,
  variables = control_lineplot_vars(
    x = "NRELTM1",
    y = "avalog",
    strata = "ARM",
    paramcd = "PARAM",
    y_unit = "AVALU"
  ),
  alt_counts_df = adsl_f,
  y_lab = "Concentration",
  y_lab_add_paramcd = FALSE,
  y_lab_add_unit = TRUE,
  interval = "mean_sdi",
  whiskers = c("mean_sdi_lwr", "mean_sdi_upr"),
  title = use_title,
  subtitle = use_subtitle,
  caption = use_footnote,
  ggtheme = theme_nest()
)

result + theme(plot.caption = element_text(hjust = 0)) +
  ggplot2::scale_y_log10(breaks = c(0.001, 0.01, 0.1, 1, 10), label = c(0.001, 0.01, 0.1, 1, 10))
```

## Teal

```{r teal, message=FALSE}
#| code-fold: show

# In progress
```

{{< include ../../si.qmd >}}

:::
