---
title: LBT07
subtitle: Laboratory Test Results with Highest NCI CTCAE Grade Post-Baseline
---

------------------------------------------------------------------------

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(scda)
library(tern)
library(dplyr)
library(forcats)

adsl <- synthetic_cdisc_dataset("rcd_2022_10_13", "adsl")
adlb <- synthetic_cdisc_dataset("rcd_2022_10_13", "adlb")

adlb_labels <- var_labels(adlb)

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
adsl <- df_explicit_na(adsl)
adlb <- df_explicit_na(adlb)

# Select worst post-baseline records.
adlb_f <- adlb %>%
  filter(!AVISIT %in% c("SCREENING", "BASELINE")) %>%
  filter(ATOXGR != "<Missing>") %>%
  filter(ONTRTFL == "Y") %>%
  filter(WGRLOFL == "Y" | WGRHIFL == "Y") %>%
  droplevels()

var_labels(adlb_f) <- adlb_labels

# Derive GRADE_DIR and GRADE_ANL to use in layout from ATOXGR
adlb_f <- adlb_f %>%
  mutate(
    GRADE_DIR = factor(
      case_when(
        ATOXGR %in% c("-1", "-2", "-3", "-4") ~ "LOW",
        ATOXGR == "0" ~ "ZERO",
        ATOXGR %in% c("1", "2", "3", "4") ~ "HIGH"
      ),
      levels = c("LOW", "ZERO", "HIGH")
    ),
    GRADE_ANL = fct_relevel(
      fct_recode(ATOXGR,
        `1` = "-1", `2` = "-2", `3` = "-3", `4` = "-4"
      ),
      c("0", "1", "2", "3", "4")
    )
  ) %>%
  var_relabel(
    GRADE_DIR = "Direction of Abnormality",
    GRADE_ANL = "Analysis Grade"
  )

# Construct analysis map
map <- unique(adlb_f[adlb_f$GRADE_DIR != "ZERO", c("PARAM", "GRADE_DIR", "GRADE_ANL")]) %>%
  lapply(as.character) %>%
  as.data.frame() %>%
  arrange(PARAM, desc(GRADE_DIR), GRADE_ANL)
```

## Standard Table

```{r variant 1}
lyt <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARMCD") %>%
  split_rows_by(
    "PARAM",
    label_pos = "topleft",
    split_label = obj_label(adlb_f$PARAM)
  ) %>%
  summarize_num_patients(
    var = "USUBJID",
    required = "ATOXGR",
    .stats = "unique_count"
  ) %>%
  split_rows_by(
    "GRADE_DIR",
    label_pos = "topleft",
    split_label = obj_label(adlb_f$GRADE_DIR),
    split_fun = trim_levels_to_map(map)
  ) %>%
  count_abnormal_by_worst_grade(
    var = "GRADE_ANL",
    variables = list(id = "USUBJID", param = "PARAM", grade_dir = "GRADE_DIR"),
    .indent_mods = 4L
  ) %>%
  append_topleft("    Highest NCI CTCAE Grade")

result <- build_table(
  lyt = lyt,
  df = adlb_f,
  alt_counts_df = adsl
)

result
```

## Teal

```{r teal, message=FALSE}
#| screenshot.opts = list(delay = 20)

library(teal.modules.clinical)
library(scda)
library(dplyr)

adsl <- synthetic_cdisc_dataset("rcd_2022_10_13", "adsl")
adlb <- synthetic_cdisc_dataset("rcd_2022_10_13", "adlb") %>%
  filter(!AVISIT %in% c("SCREENING", "BASELINE"))

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", adsl, code = 'ADSL <- synthetic_cdisc_dataset("rcd_2022_10_13", "adsl")'),
    cdisc_dataset("ADLB", adlb,
      code = 'ADLB <- synthetic_cdisc_dataset("rcd_2022_10_13", "adlb") %>%
    filter(!AVISIT %in% c("SCREENING", "BASELINE"))'
    ),
    check = TRUE
  ),
  modules = modules(
    tm_t_abnormality_by_worst_grade(
      label = "Laboratory Test Results with Highest Grade Post-Baseline",
      dataname = "ADLB",
      arm_var = choices_selected(
        choices = variable_choices(adsl, subset = c("ARM", "ARMCD")),
        selected = "ARM"
      ),
      paramcd = choices_selected(
        choices = value_choices(adlb, "PARAMCD", "PARAM"),
        selected = c("ALT", "CRP", "IGA")
      ),
      add_total = FALSE
    )
  ),
  filter = (
    list(
      ADSL = list(SAFFL = "Y"),
      ADLB = list(ONTRTFL = "Y")
    )
  )
)

shinyApp(app$ui, app$server)
```
:::
