---
title: DSUR4
subtitle: Listing of Patients Who Died During Reporting Period
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

:::: {.panel-tabset}
## Data Setup

```{r setup, message = FALSE}
#| code-fold: show

library(scda)
library(scda.2022)
library(dplyr)
library(rlistings)

adsl <- synthetic_cdisc_dataset("latest", "adsl")

out <- adsl %>%
  filter(DTHFL == "Y") %>%
  mutate(ID = paste(SITEID, SUBJID, sep = "/")) %>%
  select(ARM, ID, DTHCAUS)
death_num <- length(unique(out$ID))
var_labels(out) <- c(
  ARM = "Treatment Group",
  ID = "Center/Patient ID",
  DTHCAUS = "Cause of Death"
)
```

## Standard Listing

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("ARM"),
  disp_cols = names(out),
  main_title = "Listing of Patients Who Died During Reporting Period",
  subtitles = paste("Number of patient deaths during reporting period =", death_num)
)

head(lsting, 20)
```

`r webr_code_labels <- c("setup", "lsting")`
{{< include ../../_utils/webr.qmd >}}
:::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}

::::
