---
title: PKPL04
subtitle: Listing of Individual Drug A AUCIFO and CMAX Ratios Following Drug A or Drug B
---

------------------------------------------------------------------------

{{< include ../../test-utils/envir_hook.qmd >}}

:::: {.panel-tabset}
## Data Setup

```{r setup, message = FALSE}
#| code-fold: show

library(dplyr)
library(rlistings)
library(scda)
library(scda.2022)

adpp <- synthetic_cdisc_dataset("latest", "adpp")

visit <- "CYCLE 1 DAY 1"
drug_a <- "Plasma Drug X" # numerator drug
drug_b <- "Plasma Drug Y" # denominator drug

adpp_x <- adpp %>%
  filter(
    AVISIT == visit,
    PPCAT %in% c(drug_a, drug_b),
    PARAMCD %in% c("CMAX", "AUCIFO")
  ) %>%
  mutate(
    PARAM_U = paste0(PARAM, " (", AVALU, ")")
  )

adpp_ratio <- adpp_x %>%
  tidyr::pivot_wider(
    id_cols = c(USUBJID, PARAM_U),
    names_from = PPCAT,
    values_from = AVAL
  )

adpp_ratio[, paste0(drug_a, "/", drug_b)] <- as.numeric(unlist(adpp_ratio[, drug_a] / adpp_ratio[, drug_b]))

out <- adpp_ratio %>%
  tidyr::pivot_wider(
    id_cols = USUBJID,
    names_from = PARAM_U,
    names_glue = "{PARAM_U}\n{.value}",
    values_from = c(all_of(drug_a), all_of(drug_b), paste0(drug_a, "/", drug_b))
  ) %>%
  select(names(.)[c(1:2, 4, 6, 3, 5, 7)])

var_labels(out) <- names(out)
out <- out %>% var_relabel(USUBJID = "Subject ID")
```

## Standard Listing - CYCLE 1 DAY 1

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = "USUBJID",
  disp_cols = names(out),
  main_title = paste0(
    "Listing of Individual ", drug_a, " ", paste(unique(adpp_x$PARAM), collapse = " and "), " Ratios following ",
    unique(adpp_x$REGIMEN), " ", paste(drug_a, drug_b, sep = " or "), ", PK Population\nProtocol: xxnnnnn",
    "\nVisit: ", unique(adpp_x$AVISIT)
  ),
  subtitles = paste0("\nAnalytes: ", paste(drug_a, drug_b, sep = " and "))
)

head(lsting, 20)
```

`r webr_code_labels <- c("setup", "lsting")`
{{< include ../../webr-utils/webr.qmd >}}
:::

{{< include ../../test-utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}

::::
