---
title: PKPL01
subtitle: Listing of Drug A Plasma PK Parameters
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(rlistings)

drug_a <- "Plasma Drug X"
spec <- "Plasma"

adpp <- random.cdisc.data::cadpp
adpp_x <- adpp %>% filter(
  PPCAT == drug_a,
  PPSPEC == spec
)

out <- adpp_x %>%
  mutate(PARAM = paste0(PARAM, " (", AVALU, ")")) %>%
  select(TRT01A, USUBJID, AVISIT, PARAM, AVAL) %>%
  tidyr::pivot_wider(
    id_cols = c(TRT01A, USUBJID, AVISIT),
    names_from = PARAM,
    values_from = AVAL
  )

var_labels(out) <- names(out)
out <- out %>% var_relabel(
  TRT01A = "Treatment Group",
  USUBJID = "Subject ID",
  AVISIT = "Visit"
)
```

```{r include = FALSE}
webr_code_labels <- c("setup")
```

{{< include ../../_utils/webr_no_include.qmd >}}

## Output

:::: panel-tabset
## Standard Listing

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("TRT01A", "USUBJID", "AVISIT"),
  disp_cols = names(out),
  main_title = paste("Listing of", drug_a, spec, "PK Parameters, PK Population\nProtocol: xxnnnnn"),
  subtitles = paste("Analyte:", drug_a)
)

head(lsting, 20)
```

```{r include = FALSE}
webr_code_labels <- c("lsting")
```

{{< include ../../_utils/webr.qmd >}}
:::

## Data Setup

```{r setup}
#| code-fold: show
```
::::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}
