---
title: CML02B_GL
subtitle: Listing of Concomitant Medication Class, Preferred Name, and Investigator-Specified Terms
---

------------------------------------------------------------------------

{{< include ../../test-utils/envir_hook.qmd >}}

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(scda)
library(dplyr)
library(rlistings)

adcm <- synthetic_cdisc_dataset("latest", "adcm")

out <- adcm %>%
  select(ATC1, ATC2, ATC3, ATC4, CMDECOD, CMTRT) %>%
  unique()

var_labels(out) <- c(
  ATC1 = "ATC Class Level 1",
  ATC2 = "ATC Class Level 2",
  ATC3 = "ATC Class Level 3",
  ATC4 = "ATC Class Level 4",
  CMDECOD = "WHODrug Preferred Name",
  CMTRT = "Investigator-Specified\nTreatment Term"
)
```

## Standard Listing

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("ATC1", "ATC2", "ATC3", "ATC4", "CMDECOD", "CMTRT"),
  disp_cols = names(out),
  main_title = "Listing of Concomitant Medication Class, Preferred Name, and Investigator-Specified Terms"
)

head(lsting, 20)
```

{{< include ../../test-utils/save_results.qmd >}}

{{< include ../../si.qmd >}}
:::
