---
title: CML01
subtitle: Listing of Previous and Concomitant Medications
---

------------------------------------------------------------------------

{{< include ../../test-utils/envir_hook.qmd >}}

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(dplyr)
library(scda)
library(rlistings)

adcm <- synthetic_cdisc_dataset("latest", "adcm")

out <- adcm %>%
  filter(!is.na(CMDECOD)) %>%
  mutate(
    ID = paste(SITEID, SUBJID, sep = "/"),
    AGSXRC = paste(AGE, SEX, RACE, sep = "/"),
    TRTSD = toupper(format(as.Date(TRTSDTM), "%d%b%Y")),
    CMASTD = toupper(format(as.Date(ASTDTM), "%d%b%Y")),
    CMSTRFL = ifelse(ASTDY < 0, "Yes", "No"),
    CMENRFL = ifelse(CMENRTPT == "ONGOING", "Yes", "No")
  ) %>%
  select(
    ID, AGSXRC, TRT01A, CMDECOD, TRTSD, CMASTD, ASTDY, ADURN,
    CMSTRFL, CMENRFL, CMDOSE, CMDOSU, CMDOSFRQ, CMROUTE
  )

var_labels(out) <- c(
  ID = "Center/Patient ID",
  AGSXRC = "Age/Sex/Race",
  TRT01A = "Treatment",
  CMDECOD = "Medication Name",
  TRTSD = "Date of First\nStudy Drug\nAdministration",
  CMASTD = "Medication\nStart Date",
  ASTDY = "Study Day",
  ADURN = "Duration\n(days)",
  CMSTRFL = "Previous?",
  CMENRFL = "Ongoing\nat Final\nContact?",
  CMDOSE = "Dose",
  CMDOSU = "Dose Unit",
  CMDOSFRQ = "Frequency",
  CMROUTE = "Route"
)
```

## Standard Listing

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("ID", "AGSXRC", "TRT01A", "CMDECOD"),
  disp_cols = names(out),
  main_title = "Listing of Previous and Concomitant Medications"
)

head(lsting, 20)
```

{{< include ../../test-utils/save_results.qmd >}}

{{< include ../../si.qmd >}}
:::
