---
title: PKCL01
subtitle: Listing of Drug A Concentration by Treatment Group, Patient and Nominal Time
---

------------------------------------------------------------------------

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(rlistings)
library(scda)
library(dplyr)

adpc <- synthetic_cdisc_dataset("latest", "adpc")

analyte <- "Plasma Drug X"

out <- adpc %>%
  filter(PARAM == analyte) %>%
  select(ARM, USUBJID, VISIT, NRELTM1, ARELTM1, AVAL)

var_labels(out) <- c(
  ARM = "Treatment Group",
  USUBJID = "Subject ID",
  VISIT = "Visit",
  NRELTM1 = paste0("Nominal Sampling\nTime (", adpc$RELTMU[1], ")"),
  ARELTM1 = paste0("Actual Time\nFrom First\nDose (", adpc$RELTMU[1], ")"),
  AVAL = paste0("Concentration\n(", adpc$AVALU[1], ")")
)
```

## Standard Listing

```{r}
lsting <- as_listing(
  out,
  key_cols = c("ARM", "USUBJID", "VISIT"),
  disp_cols = names(out),
  main_title = paste("Listing of", analyte, "Concentration by Treatment Group, Subject and Nominal Time, PK Population\nProtocol: xxnnnnn"),
  subtitles = paste("Analyte:", analyte)
)

head(lsting, 20)
```
:::
