---
title: DSL02
subtitle: Listing of Patients Who Discontinued Early from Study
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

::: panel-tabset
## Data Setup

```{r setup, message = FALSE}
#| code-fold: show

library(dplyr)
library(rlistings)

adsl <- random.cdisc.data::cadsl

out <- adsl %>%
  filter(AEWITHFL == "Y") %>%
  mutate(
    ID = paste(SITEID, SUBJID, sep = "/"),
    ASR = paste(AGE, SEX, RACE, sep = "/"),
    DISCONT = ifelse(!is.na(DCSREAS) & EOSSTT != "COMPLETED", "Yes", "No"),
    SSADTM = as.POSIXct(
      strftime(TRTSDTM, format = "%Y-%m-%d %H:%M:%S"),
      format = "%Y-%m-%d",
      tz = "UTC"
    ),
    SSAEDY = as.numeric(ceiling(difftime(EOSDT, SSADTM, units = "days"))),
    RANDEDY = as.numeric(ceiling(difftime(EOSDT, RANDDT, units = "days"))),
  ) %>%
  filter(DISCONT == "Yes") %>%
  select(ID, ASR, TRT01A, SSADTM, EOSDY, SSAEDY, RANDEDY, DCSREAS)

var_labels(out) <- c(
  ID = "Center/Patient ID",
  ASR = "Age/Sex/Race",
  TRT01A = "Treatment",
  SSADTM = "Date of First\nStudy Drug\nAdministration",
  EOSDY = "Day of Last\nStudy Drug\nAdministration",
  SSAEDY = "Day of Study\nDiscontinuation\nRelative to First\nStudy Drug\nAdministration",
  RANDEDY = "Day of Study\nDiscontinuation\nRelative to\nRandomization",
  DCSREAS = "Reason for\nDiscontinuation"
)
```

## Standard Listing

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = "TRT01A",
  disp_cols = names(out),
  main_title = "Listing of Patients Who Discontinued Early from Study"
)

head(lsting, 20)
```

`r webr_code_labels <- c("setup", "lsting")` {{< include ../../_utils/webr.qmd >}}
:::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}
:::
