---
title: DTHT01
subtitle: Deaths
---

------------------------------------------------------------------------

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(tern)
library(scda)
library(dplyr)

adsl <- synthetic_cdisc_dataset("latest", "adsl")

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
adsl <- df_explicit_na(adsl) %>% filter(SAFFL == "Y")

# Reorder the levels in "DTHCAT" to put Other category at the end.
adsl$DTHCAT <- factor(adsl$DTHCAT, levels = c("ADVERSE EVENT", "PROGRESSIVE DISEASE", "OTHER", "<Missing>"))
```

## Standard Table

```{r}
lyt <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  count_values(
    "DTHFL",
    values = "Y",
    .labels = c(count_fraction = "Total number of deaths"),
    .formats = c(count_fraction = "xx (xx.x%)")
  ) %>%
  summarize_vars(vars = c("DTHCAT"), var_labels = c("Primary cause of death"))

result <- build_table(lyt, df = adsl)
result
```

## Table Selecting <br/> Sections to Display

```{r}
lyt1 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  count_values(
    "DTHFL",
    values = "Y",
    .labels = c(count_fraction = "Total number of deaths"),
    .formats = c(count_fraction = "xx (xx.x%)")
  ) %>%
  summarize_vars(vars = c("DTHCAT"), var_labels = c("Primary cause of death"))

part1 <- build_table(lyt1, df = adsl)

lyt2 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  split_rows_by("DTHCAT", split_fun = keep_split_levels("OTHER"), child_labels = "hidden") %>%
  summarize_vars(
    "DTHCAUS",
    nested = TRUE,
    .stats = "count_fraction",
    .indent_mods = c("count_fraction" = 4L)
  )

part2 <- build_table(lyt2, df = adsl) %>%
  prune_table()

lyt3 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  summarize_vars(
    vars = "LDDTHGR1",
    var_labels = "Days from last drug administration",
    show_labels = "visible"
  )

part3 <- build_table(lyt3, df = adsl)

lyt4 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  split_rows_by(
    "LDDTHGR1",
    split_fun = remove_split_levels("<Missing>"),
    split_label = "Primary cause by days from last study drug administration",
    label_pos = "visible"
  ) %>%
  summarize_vars("DTHCAT")

part4 <- build_table(lyt4, df = adsl)

# Combine tables
col_info(part2) <- col_info(part1)
col_info(part3) <- col_info(part2)
col_info(part4) <- col_info(part3)

result <- rbind(
  part1,
  part2,
  part3,
  part4
)

result
```

## Table for Studies Collecting Death <br/> Information from Public Records

```{r}
dthcaus_levels <- levels(adsl[adsl$DTHCAT == "OTHER", ]$DTHCAUS)

lyt1 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  count_values(
    "DTHFL",
    values = "Y",
    .labels = c(count_fraction = "Total number of deaths"),
    .formats = c(count_fraction = "xx (xx.x%)")
  ) %>%
  summarize_vars(
    vars = c("DTHCAT"),
    var_labels = c("Primary cause of death"),
    table_names = "primary_cause"
  )

part1 <- build_table(lyt1, df = adsl)

lyt2 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  split_rows_by(
    "DTHCAT",
    split_fun = keep_split_levels("OTHER"),
    child_labels = "hidden"
  ) %>%
  count_values(
    "DTHCAUS",
    values = dthcaus_levels[5],
    .labels = c(count_fraction = "Post study reporting of deaths"),
    .formats = c(count_fraction = "xx (xx.x%)"),
    .indent_mods = c(count_fraction = 2L),
    table_names = "post_study_deaths"
  ) %>%
  count_values(
    "DTHCAUS",
    values = dthcaus_levels[-5],
    .labels = c(count_fraction = "All other causes"),
    .formats = c(count_fraction = "xx (xx.x%)"),
    .indent_mods = c(count_fraction = 2L),
    table_names = "all_other_causes"
  )

part2 <- build_table(lyt2, df = adsl)

# Combine tables
col_info(part2) <- col_info(part1)
result <- rbind(part1, part2)

result
```

## Table Adding Details for "All other causes" <br/> Category for Studies Collecting Death <br/> Information from Public Records

```{r}
dthcaus_levels <- levels(adsl[adsl$DTHCAT == "OTHER", ]$DTHCAUS)

# create a helper variable DTHCAUS_other for part3
adsl <- adsl %>%
  mutate(
    DTHCAUS_other = ifelse(
      DTHCAT == "OTHER" & DTHCAUS != "Post-study reporting of death", as.character(DTHCAUS), NA
    )
  )
adsl$DTHCAUS_other <- factor(
  adsl$DTHCAUS_other,
  levels = c("LOST TO FOLLOW UP", "SUICIDE", "UNKNOWN", "MISSING")
)
adsl$DTHCAUS_other <- explicit_na(adsl$DTHCAUS_other)

lyt1 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  count_values(
    "DTHFL",
    values = "Y",
    .labels = c(count_fraction = "Total number of deaths"),
    .formats = c(count_fraction = "xx (xx.x%)")
  ) %>%
  summarize_vars(vars = c("DTHCAT"), var_labels = c("Primary cause of death"))

part1 <- build_table(lyt1, df = adsl)

lyt2 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  split_rows_by("DTHCAT", split_fun = keep_split_levels("OTHER"), child_labels = "hidden") %>%
  count_values(
    "DTHCAUS",
    values = dthcaus_levels[5],
    .labels = c(count_fraction = "Post study reporting of deaths"),
    .formats = c(count_fraction = "xx (xx.x%)"),
    .indent_mods = c(count_fraction = 2L),
    table_names = "post_study_deaths"
  ) %>%
  count_values(
    "DTHCAUS",
    values = dthcaus_levels[-5],
    .labels = c(count_fraction = "All other causes"),
    .formats = c(count_fraction = "xx (xx.x%)"),
    .indent_mods = c(count_fraction = 2L),
    table_names = "all_other_causes"
  )

part2 <- build_table(lyt2, df = adsl)

lyt3 <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARM", split_fun = add_overall_level("All Patients", first = FALSE)) %>%
  split_rows_by("DTHCAT", split_fun = keep_split_levels("OTHER"), child_labels = "hidden") %>%
  summarize_vars(
    "DTHCAUS_other",
    nested = TRUE,
    .stats = "count_fraction",
    .indent_mods = c("count_fraction" = 3L)
  )

part3 <- build_table(lyt3, df = adsl)

# Combine tables
col_info(part2) <- col_info(part1)
col_info(part3) <- col_info(part2)

result <- rbind(part1, part2, part3)
result
```

## Teal

```{r teal, message=FALSE}
#| code-fold: show

# In progress
```

{{< include ../../si.qmd >}}

:::
