---
title: KMG01
subtitle: Kaplan-Meier Plot
---

------------------------------------------------------------------------

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(tern)
library(scda)
library(dplyr)
library(nestcolor)

adtte <- synthetic_cdisc_dataset("rcd_2022_10_13", "adtte")
anl <- adtte %>%
  dplyr::filter(PARAMCD == "OS") %>%
  dplyr::mutate(is_event = CNSR == 0)
variables <- list(tte = "AVAL", is_event = "is_event", arm = "ARMCD")
```

## Standard Plot

```{r variant_1, fig.height=8}
result <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  annot_coxph = TRUE
)
```

## Plot of Failures

```{r variant_2, fig.height=8}
result <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  yval = "Failure",
  annot_surv_med = TRUE,
  annot_coxph = TRUE,
  font_size = 7.5,
  position_coxph = c(0.3, 0),
  position_surv_med = c(0.9, 0.3)
)
```

## Plot Without <br/> Comparative Statistics

```{r variant_3, fig.height=8}
result <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  annot_surv_med = TRUE
)
```

## Plot Without <br/> Censoring Marks

```{r variant_4, fig.height=8}
result <- g_km(
  df = anl,
  variables = variables,
  censor_show = FALSE,
  xlab = "Time (Days)",
  annot_coxph = TRUE
)
```

## Plot Modifying <br/> Censoring Marks

```{r variant_5, fig.height=8}
result <- g_km(
  df = anl,
  variables = variables,
  pch = 1,
  size = 2,
  xlab = "Time (Days)",
  annot_coxph = TRUE
)
```

## Plot Modifying Options for Statistics, <br/> Tie Handling, Stratification, etc.

```{r variant_6}
variables$strat <- c("STRATA1", "STRATA2")
result <- g_km(
  df = anl,
  variables = variables,
  control_surv = control_surv_timepoint(conf_level = 0.8),
  xlab = "Time (Days)",
  annot_coxph = TRUE,
  control_coxph_pw = control_coxph(
    pval_method = "wald",
    ties = "breslow",
    conf_level = 0.8
  )
)
```

## Teal

```{r teal, message=FALSE}
#| screenshot.opts = list(delay = 36)

library(teal.modules.clinical)
library(scda)

ADSL <- synthetic_cdisc_dataset("rcd_2022_10_13", "adsl")
ADTTE <- synthetic_cdisc_dataset("rcd_2022_10_13", "adtte")

arm_ref_comp <- list(
  ACTARMCD = list(
    ref = "ARM B",
    comp = c("ARM A", "ARM C")
  ),
  ARM = list(
    ref = "B: Placebo",
    comp = c("A: Drug X", "C: Combination")
  )
)

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", ADSL, code = 'ADSL <- synthetic_cdisc_dataset("rcd_2022_10_13", "adsl")'),
    cdisc_dataset("ADTTE", ADTTE, code = 'ADTTE <- synthetic_cdisc_dataset("rcd_2022_10_13", "adtte")'),
    check = TRUE
  ),
  modules = modules(
    tm_g_km(
      label = "KM PLOT",
      plot_height = c(600, 100, 2000),
      dataname = "ADTTE",
      arm_var = choices_selected(
        variable_choices(ADSL, c("ARM", "ARMCD", "ACTARMCD")),
        "ARM"
      ),
      paramcd = choices_selected(
        value_choices(ADTTE, "PARAMCD", "PARAM"),
        "OS"
      ),
      arm_ref_comp = arm_ref_comp,
      strata_var = choices_selected(
        variable_choices(ADSL, c("SEX", "BMRKR2")),
        "SEX"
      ),
      facet_var = choices_selected(
        variable_choices(ADSL, c("SEX", "BMRKR2")),
        NULL
      )
    )
  )
)

shinyApp(app$ui, app$server)
```
:::
