---
title: AOVT03
subtitle: ANCOVA with Consideration of Interaction
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

This example will focus on data from multiple visits and take the interaction between visits and arms into consideration.

:::: {.panel-tabset}
## Data Setup

```{r setup, message = FALSE}
#| code-fold: show

library(tern)
library(dplyr)

adsl <- random.cdisc.data::cadsl
adqs <- random.cdisc.data::cadqs

adqs_in <- adqs %>%
  filter(AVISIT %in% c("WEEK 1 DAY 8", "WEEK 2 DAY 15", "WEEK 5 DAY 36")) %>%
  droplevels() %>%
  filter(PARAM %in% c("BFI All Questions", "Fatigue Interference")) %>%
  mutate(CHG = ifelse(BMEASIFL == "Y", CHG, NA)) # only analyze evaluable population
```

## Standard Table

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, test = list(result_v1 = "result")}
result <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ARMCD", ref_group = "ARM A") %>%
  split_rows_by("PARAM", split_fun = drop_split_levels) %>%
  summarize_ancova(
    vars = "CHG",
    variables = list(arm = "ARMCD", covariates = c("BASE", "AVISIT", "AVISIT*ARMCD")),
    conf_level = 0.95,
    var_labels = "WEEK 1 DAY 8",
    table_names = "WEEK 1 DAY 8",
    interaction_y = "WEEK 1 DAY 8",
    interaction_item = "AVISIT"
  ) %>%
  summarize_ancova(
    vars = "CHG",
    variables = list(arm = "ARMCD", covariates = c("BASE", "AVISIT", "AVISIT*ARMCD")),
    conf_level = 0.95,
    var_labels = "WEEK 2 DAY 15",
    table_names = "WEEK 2 DAY 15",
    interaction_y = "WEEK 2 DAY 15",
    interaction_item = "AVISIT"
  ) %>%
  summarize_ancova(
    vars = "CHG",
    variables = list(arm = "ARMCD", covariates = c("BASE", "AVISIT", "AVISIT*ARMCD")),
    conf_level = 0.95,
    var_labels = "WEEK 5 DAY 36",
    table_names = "WEEK 5 DAY 36",
    interaction_y = "WEEK 5 DAY 36",
    interaction_item = "AVISIT"
  ) %>%
  build_table(adqs_in, alt_counts_df = adsl)

result
```

`r webr_code_labels <- c("setup", "variant1")` {{< include ../../_utils/webr.qmd >}}
:::

{{< include ../../_utils/save_results.qmd >}}

## `teal` App

```{r teal, opts.label = c("skip_if_testing", "app")}
#| code-fold: show

# In progress
```

{{< include ../../repro.qmd >}}
::::
