---
title: CFBT01
subtitle: Efficacy Data and Change from Baseline by Visit
---

------------------------------------------------------------------------

{{< include ../../test-utils/envir_hook.qmd >}}

::: panel-tabset
## Data Setup

```{r setup, message = FALSE}
#| code-fold: show

library(scda)
library(tern)
library(dplyr)

adsl <- synthetic_cdisc_dataset("latest", "adsl")
adqs <- synthetic_cdisc_dataset("latest", "adqs")

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
adsl <- df_explicit_na(adsl)
adqs <- df_explicit_na(adqs)

# This example focuses on "BFI All Questions" starting from baseline.
adqs <- adqs %>%
  dplyr::filter(
    PARAM == "BFI All Questions",
    AVISIT != "SCREENING"
  )

# Define the split function for AVISIT
split_fun <- drop_split_levels
```

## Standard Table

```{r variant1, test = list(result_v1 = "result")}
afun <- function(x, .var, .spl_context, ...) {
  n_fun <- sum(!is.na(x), na.rm = TRUE)
  if (n_fun == 0) {
    mean_sd_fun <- c(NA, NA)
    median_fun <- NA
    min_max_fun <- c(NA, NA)
  } else {
    mean_sd_fun <- c(mean(x, na.rm = TRUE), sd(x, na.rm = TRUE))
    median_fun <- median(x, na.rm = TRUE)
    min_max_fun <- c(min(x), max(x))
  }
  is_chg <- .var == "CHG"
  is_baseline <- .spl_context$value[which(.spl_context$split == "AVISIT")] == "BASELINE"
  if (is_baseline && is_chg) n_fun <- mean_sd_fun <- median_fun <- min_max_fun <- NULL

  in_rows(
    "n" = n_fun,
    "Mean (SD)" = mean_sd_fun,
    "Median" = median_fun,
    "Min - Max" = min_max_fun,
    .formats = list("n" = "xx", "Mean (SD)" = "xx.xx (xx.xx)", "Median" = "xx.xx", "Min - Max" = "xx.xx - xx.xx"),
    .format_na_strs = list("n" = "NE", "Mean (SD)" = "NE (NE)", "Median" = "NE", "Min - Max" = "NE - NE")
  )
}

lyt <- basic_table() %>%
  split_cols_by("ARM") %>%
  split_rows_by(
    "PARAM",
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adqs$PARAM)
  ) %>%
  split_rows_by(
    "AVISIT",
    split_fun = split_fun,
    label_pos = "topleft",
    split_label = obj_label(adqs$AVISIT)
  ) %>%
  split_cols_by_multivar(
    vars = c("AVAL", "CHG"),
    varlabels = c("Value at Visit", "Change from\nBaseline")
  ) %>%
  analyze_colvars(afun = afun)

result <- build_table(lyt, adqs)
result
```

{{< include ../../test-utils/save_results.qmd >}}

## `teal` App

```{r teal, opts.label = c("skip_if_testing", "app")}
library(teal.modules.clinical)

## Data reproducible code
data <- teal_data()
data <- within(data, {
  library(scda)

  ADSL <- synthetic_cdisc_dataset("latest", "adsl")
  ADQS <- synthetic_cdisc_dataset("latest", "adqs")

  # Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
  ADSL <- df_explicit_na(ADSL)
  ADQS <- df_explicit_na(ADQS)
})
datanames <- c("ADSL", "ADQS")
datanames(data) <- datanames
join_keys(data) <- default_cdisc_join_keys[datanames]

## Reusable Configuration For Modules
ADSL <- data[["ADSL"]]
ADQS <- data[["ADQS"]]

## Setup App
app <- init(
  data = data,
  modules = modules(
    tm_t_summary_by(
      label = "Efficacy Data and Change from Baseline by Visit",
      dataname = "ADQS",
      arm_var = choices_selected(
        choices = variable_choices(ADSL, c("ARM", "ARMCD")),
        selected = "ARM"
      ),
      by_vars = choices_selected(
        choices = variable_choices(ADQS, c("PARAM", "AVISIT")),
        selected = c("AVISIT")
      ),
      summarize_vars = choices_selected(
        choices = variable_choices(ADQS, c("AVAL", "CHG")),
        selected = c("AVAL", "CHG")
      ),
      useNA = "ifany",
      paramcd = choices_selected(
        choices = value_choices(ADQS, "PARAMCD", "PARAM"),
        selected = "BFIALL"
      ),
      add_total = FALSE,
      parallel_vars = TRUE
    )
  ),
  filter = teal_slices(
    teal_slice("ADQS", "AVISIT", selected = NULL),
    teal_slice("ADQS", "AVAL", selected = NULL)
  )
)

shinyApp(app$ui, app$server)
```

{{< include ../../repro.qmd >}}
:::
