---
title: MHL01
subtitle: Listing of Medical History and Concurrent Diseases
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(rlistings)

admh <- random.cdisc.data::cadmh

out <- admh %>%
  mutate(
    ASR = paste(AGE, SEX, RACE, sep = "/"),
    ID = paste(SITEID, SUBJID, sep = "/"),
    TRTSDTM = toupper(format(as.Date(TRTSDTM), "%d%b%Y")),
    ASTDTM = toupper(format(as.Date(ASTDTM), "%d%b%Y")),
    AENDTM = toupper(format(as.Date(AENDTM), "%d%b%Y"))
  ) %>%
  select(ID, ASR, TRT01A, MHBODSYS, MHDECOD, TRTSDTM, ASTDTM, ASTDY, AENDTM, AENDY, ATIREL)

var_labels(out) <- c(
  ID = "Center/Patient ID",
  ASR = "Age/Sex/Race",
  TRT01A = "Treatment",
  MHBODSYS = "SOC",
  MHDECOD = "Disease Term",
  TRTSDTM = "Date of First\nStudy Drug\nAdministration",
  ASTDTM = "Start Date\nof Disease",
  ASTDY = "Start Day\nof Disease",
  AENDTM = "End Date\nof Disease",
  AENDY = "End Day\nof Disease",
  ATIREL = "Time Relation\nof Disease"
)
```

```{r include = FALSE}
webr_code_labels <- c("setup")
```

{{< include ../../_utils/webr_no_include.qmd >}}

## Output

:::: panel-tabset
## Standard Listing

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("TRT01A", "ID", "ASR", "MHBODSYS", "MHDECOD"),
  disp_cols = names(out),
  main_title = "Listing of Medical History and Concurrent Diseases"
)

head(lsting, 20)
```

```{r include = FALSE}
webr_code_labels <- c("lsting")
```

{{< include ../../_utils/webr.qmd >}}
:::

## Data Setup

```{r setup}
#| code-fold: show
```
::::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}
