---
title: KMG01
subtitle: Kaplan-Meier Plot
---

------------------------------------------------------------------------

{{< include ../../test-utils/envir_hook.qmd >}}

::: panel-tabset
## Data Setup

```{r setup, message = FALSE}
#| code-fold: show

library(tern)
library(scda)
library(dplyr)
library(nestcolor)

adtte <- synthetic_cdisc_dataset("latest", "adtte")
anl <- adtte %>%
  dplyr::filter(PARAMCD == "OS") %>%
  dplyr::mutate(is_event = CNSR == 0)
variables <- list(tte = "AVAL", is_event = "is_event", arm = "ARMCD")
```

## Standard Plot

::: {.content-visible when-profile="development"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot1, fig.width = 9, fig.height = 6, test = list(plot_v1 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE
)
plot
```
:::

::: {.content-visible when-profile="stable"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot1-stbl, fig.height = 8, test = list(plot_v1 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE
)
plot
```
:::

## Plot of Failures

::: {.content-visible when-profile="development"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot2, fig.width = 9, fig.height = 6, test = list(plot_v2 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  yval = "Failure",
  ylim = c(0, 1),
  font_size = 8,
  annot_coxph = TRUE,
  control_annot_coxph = control_coxph_annot(x = 0.25, y = 0.85, w = 0.3)
)
plot
```
:::

::: {.content-visible when-profile="stable"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot2-stbl, fig.height = 8, test = list(plot_v2 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  yval = "Failure",
  ylim = c(0, 1),
  annot_surv_med = TRUE,
  annot_coxph = TRUE,
  font_size = 7.5,
  position_coxph = c(0.3, 0),
  position_surv_med = c(0.9, 0.3)
)
plot
```
:::

## Plot Without <br/> Comparative Statistics

::: {.content-visible when-profile="development"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot3, fig.width = 9, fig.height = 6, test = list(plot_v3 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  ylim = c(0, 1)
)
plot
```
:::

::: {.content-visible when-profile="stable"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot3-stbl, fig.height = 8, test = list(plot_v3 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_surv_med = TRUE
)
plot
```
:::

## Plot Without <br/> Censoring Marks

::: {.content-visible when-profile="development"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot4, fig.width = 9, fig.height = 6, test = list(plot_v4 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  censor_show = FALSE,
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE
)
plot
```
:::

::: {.content-visible when-profile="stable"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot4-stbl, fig.height = 8, test = list(plot_v4 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  censor_show = FALSE,
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE
)
plot
```
:::

## Plot Modifying <br/> Censoring Marks

::: {.content-visible when-profile="development"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot5, fig.width = 9, fig.height = 6, test = list(plot_v5 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  pch = 1,
  size = 2,
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE
)
plot
```
:::

::: {.content-visible when-profile="stable"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot5-stbl, fig.height = 8, test = list(plot_v5 = "plot"), opts.label = "skip_test_strict"}
plot <- g_km(
  df = anl,
  variables = variables,
  pch = 1,
  size = 2,
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE
)
plot
```
:::

## Plot Modifying Options for Statistics, <br/> Tie Handling, Stratification, etc.

::: {.content-visible when-profile="development"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot6, fig.width = 9, fig.height = 6, test = list(plot_v6 = "plot"), opts.label = "skip_test_strict"}
variables$strata <- c("STRATA1", "STRATA2")
plot <- g_km(
  df = anl,
  variables = variables,
  control_surv = control_surv_timepoint(conf_level = 0.8),
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE,
  control_coxph_pw = control_coxph(
    pval_method = "wald",
    ties = "breslow",
    conf_level = 0.8
  )
)
plot
```
:::

::: {.content-visible when-profile="stable"}
<!-- skip strict because of https://github.com/r-lib/gtable/pull/94 -->
```{r plot6-stbl, test = list(plot_v6 = "plot"), opts.label = "skip_test_strict"}
variables$strata <- c("STRATA1", "STRATA2")
plot <- g_km(
  df = anl,
  variables = variables,
  control_surv = control_surv_timepoint(conf_level = 0.8),
  xlab = "Time (Days)",
  ylim = c(0, 1),
  annot_coxph = TRUE,
  control_coxph_pw = control_coxph(
    pval_method = "wald",
    ties = "breslow",
    conf_level = 0.8
  )
)
plot
```
:::

::: {.content-visible when-profile="development"}
```{r test parameters, test = list(width = "width", height = "height"), echo=FALSE}
width <- 9
height <- 6
```
:::

{{< include ../../test-utils/save_results.qmd >}}

## `teal` App

```{r teal, opts.label = c("skip_if_testing", "app")}
library(teal.modules.clinical)

## Data reproducible code
data <- teal_data()
data <- within(data, {
  library(scda)
  ADSL <- synthetic_cdisc_dataset("latest", "adsl")
  ADTTE <- synthetic_cdisc_dataset("latest", "adtte")
})
datanames <- c("ADSL", "ADTTE")
datanames(data) <- datanames
join_keys(data) <- default_cdisc_join_keys[datanames]

arm_ref_comp <- list(
  ACTARMCD = list(
    ref = "ARM B",
    comp = c("ARM A", "ARM C")
  ),
  ARM = list(
    ref = "B: Placebo",
    comp = c("A: Drug X", "C: Combination")
  )
)

## Reusable Configuration For Modules
ADSL <- data[["ADSL"]]
ADTTE <- data[["ADTTE"]]

## Setup App
app <- init(
  data = data,
  modules = modules(
    tm_g_km(
      label = "KM PLOT",
      plot_height = c(600, 100, 2000),
      dataname = "ADTTE",
      arm_var = choices_selected(
        variable_choices(ADSL, c("ARM", "ARMCD", "ACTARMCD")),
        "ARM"
      ),
      paramcd = choices_selected(
        value_choices(ADTTE, "PARAMCD", "PARAM"),
        "OS"
      ),
      arm_ref_comp = arm_ref_comp,
      strata_var = choices_selected(
        variable_choices(ADSL, c("SEX", "BMRKR2")),
        "SEX"
      ),
      facet_var = choices_selected(
        variable_choices(ADSL, c("SEX", "BMRKR2")),
        NULL
      )
    )
  )
)

shinyApp(app$ui, app$server)
```

{{< include ../../repro.qmd >}}
:::
