---
title: CML02B_GL
subtitle: Listing of Concomitant Medication Class, Preferred Name, and Investigator-Specified Terms
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(rlistings)

adcm <- random.cdisc.data::cadcm

out <- adcm %>%
  select(ATC1, ATC2, ATC3, ATC4, CMDECOD, CMTRT) %>%
  unique()

var_labels(out) <- c(
  ATC1 = "ATC Class Level 1",
  ATC2 = "ATC Class Level 2",
  ATC3 = "ATC Class Level 3",
  ATC4 = "ATC Class Level 4",
  CMDECOD = "WHODrug Preferred Name",
  CMTRT = "Investigator-Specified\nTreatment Term"
)
```

```{r include = FALSE}
webr_code_labels <- c("setup")
```

{{< include ../../_utils/webr_no_include.qmd >}}

## Output

:::: panel-tabset
## Standard Listing

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("ATC1", "ATC2", "ATC3", "ATC4"),
  disp_cols = names(out),
  main_title = "Listing of Concomitant Medication Class, Preferred Name, and Investigator-Specified Terms"
)

head(lsting, 20)
```

```{r include = FALSE}
webr_code_labels <- c("lsting")
```

{{< include ../../_utils/webr.qmd >}}
:::

## Data Setup

```{r setup}
#| code-fold: show
```
::::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}
