---
title: CML01
subtitle: Listing of Previous and Concomitant Medications
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(rlistings)

adcm <- random.cdisc.data::cadcm

out <- adcm %>%
  filter(!is.na(CMDECOD)) %>%
  mutate(
    ID = paste(SITEID, SUBJID, sep = "/"),
    AGSXRC = paste(AGE, SEX, RACE, sep = "/"),
    TRTSD = toupper(format(as.Date(TRTSDTM), "%d%b%Y")),
    CMASTD = toupper(format(as.Date(ASTDTM), "%d%b%Y")),
    CMSTRFL = ifelse(ASTDY < 0, "Yes", "No"),
    CMENRFL = ifelse(CMENRTPT == "ONGOING", "Yes", "No")
  ) %>%
  select(
    ID, AGSXRC, TRT01A, CMDECOD, TRTSD, CMASTD, ASTDY, ADURN,
    CMSTRFL, CMENRFL, CMDOSE, CMDOSU, CMDOSFRQ, CMROUTE
  )

var_labels(out) <- c(
  ID = "Center/Patient ID",
  AGSXRC = "Age/Sex/Race",
  TRT01A = "Treatment",
  CMDECOD = "Medication Name",
  TRTSD = "Date of First\nStudy Drug\nAdministration",
  CMASTD = "Medication\nStart Date",
  ASTDY = "Study Day",
  ADURN = "Duration\n(days)",
  CMSTRFL = "Previous?",
  CMENRFL = "Ongoing\nat Final\nContact?",
  CMDOSE = "Dose",
  CMDOSU = "Dose Unit",
  CMDOSFRQ = "Frequency",
  CMROUTE = "Route"
)
```

```{r include = FALSE}
webr_code_labels <- c("setup")
```

{{< include ../../_utils/webr_no_include.qmd >}}

## Output

:::: panel-tabset
## Standard Listing

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("TRT01A", "ID", "AGSXRC", "CMDECOD"),
  disp_cols = names(out),
  main_title = "Listing of Previous and Concomitant Medications"
)

head(lsting, 20)
```

```{r include = FALSE}
webr_code_labels <- c("lsting")
```

{{< include ../../_utils/webr.qmd >}}
:::

## Data Setup

```{r setup}
#| code-fold: show
```
::::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}
