---
title: RMPT05
subtitle: Extent of Exposure by Race for Risk Management Plan
---

------------------------------------------------------------------------

{{< include ../../test-utils/envir_hook.qmd >}}

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(tern)
library(scda)
library(dplyr)

adsl <- synthetic_cdisc_dataset("latest", "adsl")
adex <- synthetic_cdisc_dataset("latest", "adex")

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
adsl <- df_explicit_na(adsl)
adex <- df_explicit_na(adex)

# Simulate ADEX records with PARAMCD == "TDURD" as they are not in the sample dataset.
set.seed(1)
adex2 <- adex %>%
  distinct(USUBJID, .keep_all = TRUE) %>%
  mutate(
    PARAMCD = "TDURD",
    PARAM = "Overall duration (days)",
    AVAL = sample(x = seq(1, 200), size = n(), replace = TRUE)
  ) %>%
  bind_rows(adex)

# Now pre-processing steps are carried out.
anl <- adex2 %>%
  filter(
    PARAMCD == "TDURD",
    PARCAT2 == "Drug A",
    SAFFL == "Y"
  ) %>%
  mutate()

adsl_f <- adsl %>% filter(adsl$SAFFL == "Y")
```

## Standard Table

```{r variant1, test = list(result_v1 = "result")}
lyt <- basic_table(
  title = "Extent of Exposure by Race: Safety-Evaluable Patients",
  main_footer = "* Person time is the sum of exposure across all patients in unit: days.",
  show_colcounts = TRUE
) %>%
  summarize_patients_exposure_in_cols(
    var = "AVAL", col_split = TRUE,
    .labels = c(n_patients = "Patients", sum_exposure = "Person time*")
  ) %>%
  analyze_patients_exposure_in_cols(
    var = "RACE",
    col_split = FALSE
  ) %>%
  append_topleft(c("", obj_label(adex$RACE)))

result <- build_table(lyt, df = anl, alt_counts_df = adsl_f)
result
```

{{< include ../../test-utils/save_results.qmd >}}

## `teal` App

```{r teal, message=FALSE, opts.label='skip_if_testing'}
#| screenshot.opts = list(delay = 10)

library(scda)
library(dplyr)
library(teal.modules.clinical)

adsl <- synthetic_cdisc_dataset("latest", "adsl")
adex <- synthetic_cdisc_dataset("latest", "adex")
labels <- var_labels(adex)

set.seed(1, kind = "Mersenne-Twister")
adex <- adex %>%
  distinct(USUBJID, .keep_all = TRUE) %>%
  mutate(
    PARAMCD = "TDURD",
    PARAM = "Overall duration (days)",
    AVAL = sample(x = seq(1, 200), size = n(), replace = TRUE),
    AVALU = "Days"
  ) %>%
  bind_rows(adex)

var_labels(adex) <- labels

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", adsl, code = 'ADSL <- synthetic_cdisc_dataset("latest", "adsl")'),
    cdisc_dataset("ADEX", adex,
      code = 'ADEX <- synthetic_cdisc_dataset("latest", "adex")
  labels <- var_labels(ADEX)
  set.seed(1, kind = "Mersenne-Twister")
  ADEX <- ADEX %>%
    distinct(USUBJID, .keep_all = TRUE) %>%
    mutate(PARAMCD = "TDURD",
           PARAM = "Overall duration (days)",
           AVAL = sample(x = seq(1, 200), size = n(), replace = TRUE),
           AVALU = "Days") %>%
    bind_rows(ADEX)
  var_labels(ADEX) <- labels'
    ),
    check = TRUE
  ),
  modules = modules(
    tm_t_exposure(
      label = "Duration of Exposure Table",
      dataname = "ADEX",
      paramcd = choices_selected(
        choices = value_choices(adex, "PARAMCD", "PARAM"),
        selected = "TDURD"
      ),
      col_by_var = choices_selected(
        choices = variable_choices(adex, subset = c("SEX", "ARM")),
        selected = NULL
      ),
      row_by_var = choices_selected(
        choices = variable_choices(adex, subset = c("RACE", "STRATA1", "SEX")),
        selected = "RACE"
      ),
      parcat = choices_selected(
        choices = value_choices(adex, "PARCAT2"),
        selected = "Drug A"
      ),
      add_total = FALSE
    )
  ),
  filter = list(
    ADSL = list(SAFFL = "Y")
  )
)

shinyApp(app$ui, app$server)
```

{{< include ../../repro.qmd >}}
:::
