---
title: ADAT04B
subtitle: Baseline Prevalence and Incidence of NAbs
---

------------------------------------------------------------------------

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(tern)
library(dplyr)
library(scda)
library(tibble)

adsl <- synthetic_cdisc_dataset("rcd_2022_10_13", "adsl")
adab <- synthetic_cdisc_dataset("rcd_2022_10_13", "adab")

combodf <- tribble(
  ~valname, ~label, ~levelcombo, ~exargs,
  "all_X", "All Drug X", c("A: Drug X", "C: Combination"), list(),
  "all_pt", "All Patients", c("A: Drug X", "B: Placebo", "C: Combination"), list()
)

# Ensure character variables are converted to factors and empty strings and NAs are explicit missing levels.
adsl <- df_explicit_na(adsl)

# Baseline Pts
adab_b <- df_explicit_na(adab) %>%
  filter(
    ABLFL == "Y",
    ADABLFL == "Y",
    PARAM %in% c(
      "ADA interpreted per sample result",
      "NAB interpreted per sample result"
    )
  ) %>%
  select(-PARAMCD, -AVALC, -AVALU) %>%
  tidyr::pivot_wider(
    names_from = PARAM,
    values_from = AVAL
  ) %>%
  mutate_at(
    c("ADA interpreted per sample result", "NAB interpreted per sample result"),
    as.logical
  ) %>%
  mutate(
    ADABLFL = ADABLFL == "Y",
    PADABLFL = `ADA interpreted per sample result` == "TRUE",
    PNABBLFL = `NAB interpreted per sample result` == "TRUE",
    NNABBLFL = `NAB interpreted per sample result` == "FALSE"
  ) %>%
  var_relabel(
    ADABLFL = "Baseline evaluable patients for ADA",
    PADABLFL = "Patients with a positive ADA sample at baseline",
    PNABBLFL = "Patients with a positive NAb sample at baseline",
    NNABBLFL = "Patients with no positive NAb sample at baseline"
  )

# Post-Baseline Evaluable Pts
adab_pb_ada <- df_explicit_na(adab) %>%
  filter(ADAPBLFL == "Y") %>%
  select(STUDYID, USUBJID, ARM, ACTARM, ADAPBLFL) %>%
  mutate(ADAPBLFL = ADAPBLFL == "Y") %>%
  distinct()

# Post-Baseline ADA Positive Pts
adab_pb_adap <- df_explicit_na(adab) %>%
  filter(
    ABLFL != "Y",
    PARAM == "ADA interpreted per sample result",
    AVALC == "POSITIVE"
  ) %>%
  mutate(ADAPFL = AVALC == "POSITIVE") %>%
  select(STUDYID, USUBJID, ARM, ACTARM, ADAPFL) %>%
  distinct()

# Post-Baseline NAb Positive Pts
adab_pb_nabp <- df_explicit_na(adab) %>%
  filter(
    ABLFL != "Y",
    PARAM == "NAb interpreted per sample result",
    AVALC == "POSITIVE"
  ) %>%
  mutate(NABPFL = AVALC == "POSITIVE") %>%
  select(STUDYID, USUBJID, ARM, ACTARM, NABPFL) %>%
  distinct()

# Post-Baseline NAb Negative Pts
adab_pb_nabn <- df_explicit_na(adab) %>%
  filter(
    ABLFL != "Y",
    PARAM == "NAb interpreted per sample result",
    AVALC == "NEGATIVE"
  ) %>%
  rename(NABNFL = AVALC) %>%
  select(STUDYID, USUBJID, ARM, ACTARM, NABNFL) %>%
  distinct()

mergecol <- c("STUDYID", "USUBJID", "ARM", "ACTARM")

adab_pb <- left_join(adab_pb_ada, adab_pb_adap, by = mergecol) %>%
  left_join(adab_pb_nabp, by = mergecol) %>%
  mutate(
    NABNFL = ifelse(is.na(NABPFL), "TRUE", "FALSE"),
    NABNFL = NABNFL == "TRUE"
  ) %>%
  var_relabel(
    ADAPBLFL = "Post-baseline evaluable patients for ADA",
    ADAPFL = "Patients positive for ADA",
    NABPFL = "Patients positive for NAb",
    NABNFL = "Patients negative for NAb"
  )
```

## Standard Table

```{r}
# Layout for Baseline Prevalence of NAbs
lyt_bl <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by(
    "ACTARM",
    split_fun = add_combo_levels(combodf)
  ) %>%
  count_patients_with_flags(
    "USUBJID",
    flag_variables = formatters::var_labels(adab_b[, c("ADABLFL", "PADABLFL")]),
    .stats = "count",
    var_labels = "Baseline Prevalence of NAbs",
    show_labels = "visible",
    table_names = "t1"
  ) %>%
  count_patients_with_flags(
    "USUBJID",
    flag_variables = var_labels(adab_b[, "PNABBLFL"]),
    table_names = "t2",
    .indent_mods = 1L,
    show_labels = "hidden"
  ) %>%
  count_patients_with_flags(
    "USUBJID",
    flag_variables = var_labels(adab_b[, "NNABBLFL"]),
    .stats = "count",
    table_names = "t3",
    .indent_mods = 1L,
    show_labels = "hidden"
  )

# Layout for incidence of NAbs
lyt_pb <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by(
    "ACTARM",
    split_fun = add_combo_levels(combodf)
  ) %>%
  count_patients_with_flags(
    "USUBJID",
    flag_variables = formatters::var_labels(adab_pb[, c("ADAPBLFL", "ADAPFL")]),
    .stats = "count",
    var_labels = "Incidence of NAbs",
    show_labels = "visible",
    table_names = "tb1"
  ) %>%
  count_patients_with_flags(
    "USUBJID",
    flag_variables = formatters::var_labels(data.frame(NABPFL = adab_pb[, "NABPFL"])),
    table_names = "tb2",
    .indent_mods = 1L,
    show_labels = "hidden"
  ) %>%
  count_patients_with_flags(
    "USUBJID",
    flag_variables = var_labels(data.frame(NABNFL = adab_pb[, "NABNFL"])),
    .stats = "count",
    table_names = "tb3",
    .indent_mods = 1L,
    show_labels = "hidden"
  )

result_1 <- build_table(lyt_bl, df = adab_b, alt_counts_df = adsl)
result_2 <- build_table(lyt_pb, df = adab_pb, alt_counts_df = adsl)

# Combine tables.
result <- rbind(result_1, result_2)

# Change the column order.
result <- cbind_rtables(result[, 1], result[, 3]) %>%
  cbind_rtables(result[, 4]) %>%
  cbind_rtables(result[, 2]) %>%
  cbind_rtables(result[, 5])

main_title(result) <- paste(
  "Baseline Prevalence and Incidence of Neutralizing Antibodies (NAbs)"
)
subtitles(result) <- paste("Protocol:", unique(adab$PARCAT1)[1])
main_footer(result) <- paste(
  "NAb = Neutralizing Antibodies ADA = Anti-Drug Antibodies (is also referred to as ATA, or Anti-Therapeutic Antibodies) Baseline evaluable patient for ADA = a patient with an ADA assay result from a baseline sample(s) Baseline evaluable patient for NAb = a patient with a NAb assay result from a baseline sample(s) Post-baseline evaluable patient for ADA = a patient with an ADA assay result from at least one post-baseline sample Post-baseline evaluable patient for NAb = a patient with a NAb assay result from at least one post-baseline sample Number of patients positive for ADA = the number of post-baseline evaluable patients for ADA determined to have Treatment Emergent ADA during the study period.
Number of patients positive for NAb = the number (and percentage) of post-baseline evaluable patients for ADA determined to have at least one positive post-baseline NAb result during the study period. Number of patients negative for NAb = number of post-baseline evaluable patients with all negative post-baseline NAb results."
)
result
```

## Teal

```{r teal, message=FALSE}
#| code-fold: show

# In progress
```
:::
