---
title: VSL01
subtitle: 'Listing of Vital Signs: Safety-Evaluable Patients'
---

------------------------------------------------------------------------

{{< include ../../test-utils/envir_hook.qmd >}}

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(dplyr)
library(scda)
library(rlistings)

advs <- synthetic_cdisc_dataset("latest", "advs")

get_param_unit_range <- function(dataset) {
  u_rng <- lapply(unique(dataset$PARAMCD), function(p) {
    dat <- dataset %>% filter(PARAMCD == p)
    list(
      unit = unique(dat$AVALU),
      range = paste0(unique(dat$ANRLO), "-", unique(dat$ANRHI))
    )
  })
  names(u_rng) <- unique(dataset$PARAMCD)
  u_rng
}

vs_u_rng <- get_param_unit_range(advs)

advs_sub <- advs %>%
  filter(!is.na(AVAL) & SAFFL == "Y" & ONTRTFL == "Y" & !is.na(VSSEQ)) %>%
  mutate(
    CRTNPT = paste(SITEID, sub("^.*-([[:alnum:]]+)$", "\\1", SUBJID), sep = "/"),
    AGSXRC = paste(AGE, SEX, RACE, sep = "/"),
    AVAL = format(round(AVAL, 2), nsmall = 2),
    AVAL_ANRIND = ifelse(ANRIND %in% c("NORMAL", ""), AVAL, paste(AVAL, substr(ANRIND, 1, 1), sep = "/")),
    CHG = format(round(CHG, 2), nsmall = 2)
  )

anl_vs <- advs_sub %>%
  select(SUBJID, CRTNPT, AGSXRC, TRT01A, PARAMCD, AVAL_ANRIND, CHG, ADY, AVISIT, ADTM) %>%
  tidyr::pivot_wider(
    id_cols = c(SUBJID, CRTNPT, AGSXRC, TRT01A, ADY, AVISIT, ADTM),
    names_from = PARAMCD,
    values_from = c(AVAL_ANRIND, CHG)
  )

out <- anl_vs %>%
  select(
    CRTNPT, AGSXRC, TRT01A, AVISIT, ADY, AVAL_ANRIND_WEIGHT, CHG_WEIGHT, AVAL_ANRIND_TEMP, CHG_TEMP, AVAL_ANRIND_DIABP,
    CHG_DIABP, AVAL_ANRIND_SYSBP, CHG_SYSBP, AVAL_ANRIND_PULSE, CHG_PULSE, AVAL_ANRIND_RESP, CHG_RESP
  ) %>%
  var_relabel(
    CRTNPT = "Center/Subject ID",
    AGSXRC = "Age/Sex/Race",
    TRT01A = "Treatment",
    AVISIT = "Visit",
    ADY = "Study\nDay",
    AVAL_ANRIND_WEIGHT = paste0("Weight\nResult\n(", vs_u_rng$WEIGHT$unit, ");\nRange:(", vs_u_rng$WEIGHT$range, ")"),
    CHG_WEIGHT = "Weight\nChange from BL",
    AVAL_ANRIND_TEMP = paste0("Temperature Result\n(", vs_u_rng$TEMP$unit, ");\nRange:(", vs_u_rng$TEMP$range, ")"),
    CHG_TEMP = "Temperature Rate\nChange from BL",
    AVAL_ANRIND_DIABP = paste0("Diastolic Blood\nPressure,\nSitting\nResult\n(", vs_u_rng$DIABP$unit, ");\nRange:(", vs_u_rng$DIABP$range, ")"),
    CHG_DIABP = "Diastolic Blood\nPressure,\nSitting\nChange from BL",
    AVAL_ANRIND_SYSBP = paste0("Systolic Blood\nPressure,\nSitting\n(", vs_u_rng$SYSBP$unit, ");\nRange:(", vs_u_rng$SYSBP$range, ")"),
    CHG_SYSBP = "Systolic Blood\nPressure,\nSitting\nChange from BL",
    AVAL_ANRIND_PULSE = paste0("Pulse Rate Result\n(", vs_u_rng$PULSE$unit, ");\nRange:(", vs_u_rng$PULSE$range, ")"),
    CHG_PULSE = "Pulse Rate\nChange from BL",
    AVAL_ANRIND_RESP = paste0("Respiratory Rate\nResult\n(", vs_u_rng$RESP$unit, ");\nRange:(", vs_u_rng$RESP$range, ")"),
    CHG_RESP = "Respiratory Rate\nChange from BL"
  )
```

## Standard Listing

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("CRTNPT", "AGSXRC", "TRT01A", "AVISIT"),
  disp_cols = names(out),
  main_title = "Listing of Vital Signs: Safety-Evaluable Patients",
  main_footer = "Baseline is the patient's last observation prior to initiation of study drug. Abnormalities are flagged as high (H) or low (L) if
  outside the Roche standard reference range."
)

head(lsting, 20)
```

{{< include ../../test-utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}
:::
