---
title: EXL01
subtitle: Listing of Exposure to Study Drug
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(rlistings)

adex <- random.cdisc.data::cadex

out <- adex %>%
  filter(PARAMCD == "DOSE" & !is.na(AVAL) & SAFFL == "Y") %>%
  mutate(
    CRTNPT = paste(SITEID, SUBJID, sep = "/")
  ) %>%
  arrange(CRTNPT, AVISIT) %>%
  select(CRTNPT, AVISIT, EXSTDY, EXENDY, TRT01A, AVAL, AVALU, EXDOSFRQ, EXROUTE)

var_labels(out) <- c(
  CRTNPT = "Center/Subject ID",
  AVISIT = "Visit",
  EXSTDY = "Study Day\nFrom",
  EXENDY = "Study Day\nTo",
  TRT01A = "Treatment",
  AVAL = "Dose",
  AVALU = "Unit",
  EXDOSFRQ = "Frequency",
  EXROUTE = "Route"
)
```

```{r include = FALSE}
webr_code_labels <- c("setup")
```

{{< include ../../_utils/webr_no_include.qmd >}}

## Output

:::: panel-tabset
## Standard Listing

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r lsting, test = list(lsting = "lsting")}
lsting <- as_listing(
  out,
  key_cols = c("TRT01A", "CRTNPT", "AVISIT"),
  disp_cols = names(out),
  main_title = "Listing of Exposure to Study Drug"
)

head(lsting, 20)
```

```{r include = FALSE}
webr_code_labels <- c("lsting")
```

{{< include ../../_utils/webr.qmd >}}
:::

## Data Setup

```{r setup}
#| code-fold: show
```
::::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}