---
title: PDT02
subtitle: Major Protocol Deviations Related to Epidemic/Pandemic
---

------------------------------------------------------------------------

{{< include ../../_utils/envir_hook.qmd >}}

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(tern)
library(dplyr)

adsl <- random.cdisc.data::cadsl
addv <- random.cdisc.data::caddv

adsl <- df_explicit_na(adsl)
addv <- df_explicit_na(addv)

addv_pan <- addv %>%
  filter(AEPRELFL == "Y" & DVCAT == "MAJOR") %>%
  var_relabel(
    DVREAS = "Primary Reason",
    DVTERM = "Description"
  )
```

```{r include = FALSE}
webr_code_labels <- c("setup")
```

{{< include ../../_utils/webr_no_include.qmd >}}

## Output

:::: panel-tabset
## Standard Table

::: {.panel-tabset .nav-justified group="webr"}
## {{< fa regular file-lines sm fw >}} Preview

```{r variant1, test = list(result_v1 = "result")}
lyt <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ACTARM") %>%
  analyze_num_patients(
    vars = "USUBJID",
    .stats = c("unique", "nonunique"),
    .labels = c(
      unique = "Total number of patients with at least one major protocol deviation related to epidemic/pandemic",
      nonunique = "Total number of major protocol deviations related to epidemic/pandemic"
    )
  ) %>%
  split_rows_by(
    "DVREAS",
    split_fun = drop_split_levels,
    nested = FALSE,
    label_pos = "topleft",
    split_label = obj_label(addv_pan$DVREAS)
  ) %>%
  summarize_num_patients(
    var = "USUBJID",
    .stats = c("unique"),
    .labels = "Site action due to epidemic/pandemic"
  ) %>%
  count_occurrences(vars = "DVTERM") %>%
  append_varlabels(addv_pan, "DVTERM", indent = 1L)

result <- build_table(lyt, addv_pan, alt_counts_df = adsl)
result
```

```{r include = FALSE}
webr_code_labels <- c("variant1")
```

{{< include ../../_utils/webr.qmd >}}
:::

## Data Setup

```{r setup}
#| code-fold: show
```
::::

{{< include ../../_utils/save_results.qmd >}}

{{< include ../../repro.qmd >}}