---
title: PDT02
subtitle: Major Protocol Deviations Related to Epidemic/Pandemic
---

------------------------------------------------------------------------

::: panel-tabset
## Data Setup

```{r setup, message=FALSE}
#| code-fold: show

library(scda)
library(tern)
library(dplyr)

adsl <- synthetic_cdisc_dataset("rcd_2022_10_13", "adsl")
addv <- synthetic_cdisc_dataset("rcd_2022_10_13", "addv")
adsl <- df_explicit_na(adsl)
addv <- df_explicit_na(addv)
addv_pan <- addv %>% filter(AEPRELFL == "Y" & DVCAT == "MAJOR")
```

## Standard Table

```{r pdt02}
lyt <- basic_table(show_colcounts = TRUE) %>%
  split_cols_by("ACTARM") %>%
  analyze_num_patients(
    vars = "USUBJID",
    .stats = c("unique", "nonunique"),
    .labels = c(
      unique = "Total number of patients with at least one major protocol deviation related to epidemic/pandemic",
      nonunique = "Total number of major protocol deviations related to epidemic/pandemic"
    )
  ) %>%
  split_rows_by(
    "DVREAS",
    split_fun = drop_split_levels,
    nested = FALSE,
    label_pos = "topleft",
    split_label = obj_label(addv_pan$DVREAS)
  ) %>%
  summarize_num_patients(
    var = "USUBJID",
    .stats = c("unique_count")
  ) %>%
  count_occurrences(vars = "DVTERM") %>%
  append_varlabels(addv_pan, "DVTERM", indent = 1L)

result <- build_table(lyt, addv_pan, alt_counts_df = adsl)
result
```

## Teal

```{r teal, message=FALSE}
#| code-fold: show

# In progress
```

{{< include ../../si.qmd >}}

:::
