#!/bin/sh

# See https://github.com/insightsengineering/tlg-catalog/issues/272
# This script addresses R CMD CHECK notes caused by the tests/testthat/_book symlink.
# It renders the book (which saves the output for snapshot testing) and removes the symlink.
# Executed during the R CMD BUILD "running ‘cleanup’" step, it ensures a smaller package tarball without the symlink and eliminates R CMD CHECK notes.

TLG_CATALOG_PKG_TEST_DATA_PATH=$(realpath "./tests/testthat/_data")
export TLG_CATALOG_PKG_TEST_DATA_PATH
if [ "$TLG_CATALOG_PKG_BUILD_RENDER" = "TRUE" ]; then
  echo "Rendering Quarto book..."
  quarto render tests/testthat/_book/ --no-cache
  echo "Quarto book rendered."
else
  echo "Skipping Quarto book rendering."
fi

rm -rf tests/testthat/_book

exit 0