---
website:
  title: TLG Catalog - Stable
  navbar:
    right:
      - text: "Stable"
        menu:
          - text: "Dev"
            href: "https://insightsengineering.github.io/tlg-catalog/development"
      - icon: slack
        href: https://app.slack.com/client/T028PB489D3/
        aria-label: Slack
      - icon: github
        href: https://github.com/insightsengineering/tlg-catalog
        aria-label: Repository

webr:
  repos:
    - https://insightsengineering.r-universe.dev/