website:
  title: TLG Catalog - Stable
  navbar:
    right:
      - icon: slack
        href: https://app.slack.com/client/T028PB489D3/
        aria-label: Slack
      - icon: github
        href: https://github.com/insightsengineering/tlg-catalog
        aria-label: Repository
      - text: "Stable version"
        menu:
          - text: "Development version"
            href: "https://walkowif.github.io/tlg-catalog/development"
