## Reproducibility

### Timestamp

```{r systime, message=FALSE}
#| code-fold: show
#| renv.ignore: TRUE

Sys.time()
```

### Session Info

```{r sessioninfo, message=FALSE}
#| code-fold: show
#| renv.ignore: TRUE

sessionInfo()
```

### `.lock` file

Download the `.lock` file and use [`renv::restore()`](https://rstudio.github.io/renv/reference/restore.html) on it to recreate environment used to generate this website.

```{r snapshot, message=FALSE, opts.label='skip_if_testing'}
#| code-fold: true
#| renv.ignore: TRUE

parent_file_path <- knitr::current_input(dir = TRUE)

book_root_dir <- parent_file_path
while (!file.exists(file.path(book_root_dir, "_quarto.yml"))) book_root_dir <- dirname(book_root_dir)

lock_path <- file.path(
  "../../assets/www/lock",
  paste0(
    gsub(
      file.path(book_root_dir, ""),
      "",
      gsub(
        "\\.rmarkdown$",
        "",
        knitr::current_input(dir = TRUE)
      )
    ),
    ".lock"
  )
)

withr::with_options(
  list(renv.verbose = FALSE),
  renv::snapshot(parent_file_path, lockfile = lock_path, prompt = FALSE, force = TRUE)
)
```

[Download](`r if(exists("lock_path")) lock_path else "test"`)
