---
title: Index
toc: true
toc-depth: 4
---

------------------------------------------------------------------------

### **Tables**

#### Adverse Events

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET01 -- Safety Summary](./book/tables/adverse-events/aet01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET01_AESI -- Safety Summary (Adverse Events of Special Interest)](./book/tables/adverse-events/aet01_aesi.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET02 -- Adverse Events](./book/tables/adverse-events/aet02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET02_SMQ -- Adverse Events by Standardized MedDRA Query](./book/tables/adverse-events/aet02_smq.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET03 -- Adverse Events by Greatest Intensity](./book/tables/adverse-events/aet03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET04 -- Adverse Events by Highest NCI CTCAE Grade](./book/tables/adverse-events/aet04.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET04_PI -- Adverse Events Reported in $\geq$ 10% of Patients by Highest NCI CTCAE Grade](./book/tables/adverse-events/aet04_pi.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET05 -- Adverse Event Rate Adjusted for Patient-Years at Risk -- First Occurrence](./book/tables/adverse-events/aet05.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET05_ALL -- Adverse Event Rate Adjusted for Patient-Years at Risk -- All Occurrences](./book/tables/adverse-events/aet05_all.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET06 -- Adverse Events by Baseline Characteristic](./book/tables/adverse-events/aet06.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET06_SMQ -- Adverse Events by Baseline Characteristic, by SMQ and Preferred Term](./book/tables/adverse-events/aet06_smq.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET07 -- Adverse Events Resulting in Death](./book/tables/adverse-events/aet07.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET09 -- Adverse Events Related to Study Drug](./book/tables/adverse-events/aet09.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET09_SMQ -- Adverse Events Related to Study Drug by Standardized MedDRA Query](./book/tables/adverse-events/aet09_smq.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AET10 -- Most Common ($\geq$ 5%) Adverse Events](./book/tables/adverse-events/aet10.qmd)


#### Efficacy

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AOVT01 -- ANCOVA for Multiple End Points](./book/tables/efficacy/aovt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CFBT01 -- Efficacy Data and Change from Baseline by Visit](./book/tables/efficacy/cfbt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[COXT01 -- Cox Regression](./book/tables/efficacy/coxt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[COXT02 -- Multivariable Cox Regression](./book/tables/efficacy/coxt02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DORT01 -- Duration of Response](./book/tables/efficacy/dort01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LGRT02 -- Multi-Variable Logistic Regression](./book/tables/efficacy/lgrt02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[MMRMT01 -- Tables for Mixed-Effect Model Repeated Measures Analysis](./book/tables/efficacy/mmrmt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ONCT05 -- Objective Response Rate by Subgroup](./book/tables/efficacy/onct05.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[RSPT01 -- Best Overall Response](./book/tables/efficacy/rspt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[TTET01 -- Time-To-Event Summary](./book/tables/efficacy/ttet01.qmd)


#### Lab Results

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT01 -- Laboratory Test Results and Change from Baseline by Visit](./book/tables/lab-results/lbt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT02 -- Laboratory Test Results by Visit](./book/tables/lab-results/lbt02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT03 -- Laboratory Test Results Change from Baseline by Visit](./book/tables/lab-results/lbt03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT04 -- Laboratory Abnormalities Not Present at Baseline](./book/tables/lab-results/lbt04.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT05 -- Laboratory Abnormalities with Single and Replicated Marked](./book/tables/lab-results/lbt05.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT06 -- Laboratory Abnormalities by Visit and Baseline Status](./book/tables/lab-results/lbt06.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT07 -- Laboratory Test Results with Highest NCI CTCAE Grade Post-Baseline](./book/tables/lab-results/lbt07.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT08 -- Laboratory Test Results with Highest NCI CTCAE Grade at Any Time](./book/tables/lab-results/lbt08.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT09 -- Liver Laboratory Tests -- Patients with Elevated Post-Baseline AST or ALT Levels](./book/tables/lab-results/lbt09.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT10 -- Liver Laboratory Tests -- Patients with Elevated Post-Baseline AST or ALT Levels at Two Consecutive Visits (with Respect to ULN)](./book/tables/lab-results/lbt10.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT10_BL -- Liver Laboratory Tests -- Patients with Elevated Post-Baseline AST or ALT Levels at Two Consecutive Visits (with Respect to Baseline)](./book/tables/lab-results/lbt10_bl.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT11 -- Time to First Increase in Liver Laboratory Test Result Meeting Hy's Law Laboratory Critieria (with Respect to ULN)](./book/tables/lab-results/lbt11.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT11_BL -- Time to First Increase in Liver Laboratory Test Result Meeting Hy's Law Laboratory Critieria (with Respect to Baseline)](./book/tables/lab-results/lbt11_bl.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT12 -- Liver Laboratory Tests by Time on Treatment -- Patients with Elevated Post-Baseline AST or ALT Levels (with Respect to ULN)](./book/tables/lab-results/lbt12.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT12_BL -- Liver Laboratory Tests by Time on Treatment -- Patients with Elevated Post-Baseline AST or ALT Levels (with Respect to Baseline)](./book/tables/lab-results/lbt12_bl.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT13 -- NCI CTCAE Grade Laboratory Abnormalities by Visit and Baseline Grade](./book/tables/lab-results/lbt13.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT14 -- Laboratory Test Results Shift Table -- Highest NCI CTCAE Grade Post-Baseline by Baseline NCI CTCAE Grade](./book/tables/lab-results/lbt14.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBT15 -- Laboratory Test Shifts to NCI CTCAE Grade 3-4 Post-Baseline](./book/tables/lab-results/lbt15.qmd)


#### Pharmacokinetic

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ADAT01 -- Baseline Prevalence and Incidence of Treatment Emergent ADA](./book/tables/pharmacokinetic/adat01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ADAT02 -- Summary of Patients with Treatment-Induced ADA](./book/tables/pharmacokinetic/adat02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ADAT03 -- Summary of Serum Concentrations at Timepoints Where ADA Samples Were Collected and Analyzed](./book/tables/pharmacokinetic/adat03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ADAT04A -- Baseline Prevalence and Incidence of Treatment Emergent NAbs](./book/tables/pharmacokinetic/adat04a.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ADAT04B -- Baseline Prevalence and Incidence of NAbs](./book/tables/pharmacokinetic/adat04b.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKCT01 -- Summary Concentration Table](./book/tables/pharmacokinetic/pkct01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPT02 -- Pharmacokinetic Parameter Summary -- Plasma/Serum/Blood PK Parameters (Stats in Rows)](./book/tables/pharmacokinetic/pkpt02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPT03 -- Pharmacokinetic Parameter Summary of Plasma by Treatment (Stats in Columns)](./book/tables/pharmacokinetic/pkpt03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPT04 -- Pharmacokinetic Parameter Summary -- Urine PK Parameters (Stats in Rows)](./book/tables/pharmacokinetic/pkpt04.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPT05 -- Summary of Urinary PK Parameters by Treatment Arm (Stats in Columns)](./book/tables/pharmacokinetic/pkpt05.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPT06 -- Pharmacokinetic Parameter Summary -- Dose-Normalized PK Parameters (Stats in Rows)](./book/tables/pharmacokinetic/pkpt06.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPT07 -- Table of Mean Dose-Normalized Selected Pharmacokinetic Parameters (Stats in Columns)](./book/tables/pharmacokinetic/pkpt07.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPT08 -- Pharmacokinetic Parameter Summary of Cumulative Amount of Drug Eliminated and Cumulative Percentage of Drug Recovered (Stats in Columns)](./book/tables/pharmacokinetic/pkpt08.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPT11 -- Pharmacokinetic Parameter Estimated Ratios of Geometric Means and 90% Confidence Intervals for AUC and CMAX](./book/tables/pharmacokinetic/pkpt11.qmd)


#### Safety

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CMT01 -- Concomitant Medications (GNEDrug Legacy Coding)](./book/tables/safety/cmt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CMT01A -- Concomitant Medications by Medication Class and Preferred Name](./book/tables/safety/cmt01a.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CMT01B -- Concomitant Medications by Medication Class and Preferred Name](./book/tables/safety/cmt01b.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CMT02_PT -- Concomitant Medications by Preferred Name (WHODrug Coding)](./book/tables/safety/cmt02_pt.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DMT01 -- Demographics and Baseline Characteristics](./book/tables/safety/dmt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DST01 -- Patient Disposition](./book/tables/safety/dst01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DTHT01 -- Deaths](./book/tables/safety/dtht01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EGT01 -- ECG Results and Change from Baseline by Visit](./book/tables/safety/egt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EGT02 -- ECG Abnormalities (EGT02_1 & EGT02_2)](./book/tables/safety/egt02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EGT03 -- Shift Table of ECG Interval Data -- Baseline Versus Minimum/Maximum Post-Baseline](./book/tables/safety/egt03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EGT04 -- Shift Table of Qualitative ECG Assessments](./book/tables/safety/egt04.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EGT05_QTCAT -- ECG Actual Values and Changes from Baseline by Visit](./book/tables/safety/egt05_qtcat.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ENTXX -- Enrollment Variants](./book/tables/safety/enrollment01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EUDRAT01 -- Non-Serious Adverse Events Reported in $\geq$ 5% of Patients in Any Treatment Group -- Patients and Events](./book/tables/safety/eudrat01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EUDRAT02 -- Serious Adverse Events, Fatal Serious Adverse Events, and Serious Adverse Events Related to Study Medication](./book/tables/safety/eudrat02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EXT01 -- Study Drug Exposure Table](./book/tables/safety/ext01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[MHT01 -- Medical History](./book/tables/safety/mht01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PDT01 -- Major Protocol Deviations](./book/tables/safety/pdt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PDT02 -- Major Protocol Deviations Related to Epidemic/Pandemic](./book/tables/safety/pdt02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[VST01 -- Vital Sign Results and Change from Baseline by Visit](./book/tables/safety/vst01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[VST02 -- Vital Sign Abnormalities](./book/tables/safety/vst02.qmd)


#### Other

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AOVT02 -- ANCOVA with Single End Point and Customized Table](./book/tables/other/aovt02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AOVT03 -- ANCOVA with Consideration of Interaction](./book/tables/other/aovt03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CMHT01 -- Cochran-Mantel-Haenszel (CMH) Summary](./book/tables/other/cmht01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DISCLOSUREST01 -- Disclosures Outputs](./book/tables/other/disclosurest01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[RATET01 -- Event Rate Summary for Recurrent Events](./book/tables/other/ratet01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[RBMIT01 -- Tables for RBMI](./book/tables/other/rbmit01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[RMPT01 -- Duration of Exposure for Risk Management Plan](./book/tables/other/rmpt01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[RMPT03 -- Extent of Exposure by Age Group and Gender for Risk Management Plan](./book/tables/other/rmpt03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[RMPT04 -- Extent of Exposure by Ethnic Origin for Risk Management Plan](./book/tables/other/rmpt04.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[RMPT05 -- Extent of Exposure by Race for Risk Management Plan](./book/tables/other/rmpt05.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[RMPT06 -- Seriousness, Outcomes, Severity, Frequency with 95% CI for Risk Management Plan](./book/tables/other/rmpt06.qmd)


------------------------------------------------------------------------

### **Listings**

#### Pharmacokinetic

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ADAL01 -- Listing of Anti-Drug Antibody Data for Patients with At Least One ADA Sample Datum by Treatment](./book/listings/pharmacokinetic/adal01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ADAL02 -- Listing of Anti-Drug Antibody Data for Treatment Emergent ADA Positive Patients](./book/listings/pharmacokinetic/adal02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKCL01 -- Listing of Drug A Concentration by Treatment Group, Patient and Nominal Time](./book/listings/pharmacokinetic/pkcl01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKCL02 -- Listing of Drug A Urine Concentration and Volumes](./book/listings/pharmacokinetic/pkcl02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPL01 -- Listing of Drug A Plasma PK Parameters](./book/listings/pharmacokinetic/pkpl01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPL02 -- Listing of Drug A Urine PK Parameters](./book/listings/pharmacokinetic/pkpl02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPL04 -- Listing of Individual Drug A AUCIFO and CMAX Ratios Following Drug A or Drug B](./book/listings/pharmacokinetic/pkpl04.qmd)


#### Other

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AEL01 -- Listing of Preferred Terms, Lowest Level Terms, and Investigator-Specified Adverse Event Terms](./book/listings/other/ael01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AEL01_NOLLT -- Listing of Preferred Terms and Investigator-Specified Adverse Event Terms](./book/listings/other/ael01_nollt.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AEL02 -- Listing of Adverse Events](./book/listings/other/ael02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AEL02_ED -- Listing of Adverse Events (for Early Development Studies)](./book/listings/other/ael02_ed.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AEL03 -- Listing of Serious Adverse Events](./book/listings/other/ael03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[AEL04 -- Listing of Patient Deaths](./book/listings/other/ael04.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CML01 -- Listing of Previous and Concomitant Medications](./book/listings/other/cml01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CML02A_GL -- Listing of Concomitant Medication Class Level 2, Preferred Name, and Investigator-Specified Terms](./book/listings/other/cml02a_gl.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CML02B_GL -- Listing of Concomitant Medication Class, Preferred Name, and Investigator-Specified Terms](./book/listings/other/cml02b_gl.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DSL01 -- Listing of Patients with Study Drug Withdrawn Due to Adverse Events](./book/listings/other/dsl01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DSL02 -- Listing of Patients Who Discontinued Early from Study](./book/listings/other/dsl02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[DSUR4 -- Listing of Patients Who Died During Reporting Period](./book/listings/other/dsur4.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EGL01 -- 'Listing of ECG Data: Safety-Evaluable Patients'](./book/listings/other/egl01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[EXL01 -- Listing of Exposure to Study Drug](./book/listings/other/exl01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBL01 -- Listing of Laboratory Test Results](./book/listings/other/lbl01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBL01_RLS -- Listing of Laboratory Test Results Using Roche Safety Lab Standardization](./book/listings/other/lbl01_rls.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBL02A -- Listing of Laboratory Abnormalities (constant units)](./book/listings/other/lbl02a.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBL02A_RLS -- Listing of Laboratory Abnormalities Defined by Roche Safety Lab Standardization](./book/listings/other/lbl02a_rls.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LBL02B -- Listing of Laboratory Abnormalities (variable units)](./book/listings/other/lbl02b.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[MHL01 -- Listing of Medical History and Concurrent Diseases](./book/listings/other/mhl01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ONCL01 -- Listing of Individual Efficacy Data](./book/listings/other/oncl01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[VSL01 -- 'Listing of Vital Signs: Safety-Evaluable Patients'](./book/listings/other/vsl01.qmd)


------------------------------------------------------------------------

### **Graphs**

#### Pharmacokinetic

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKCG01 -- Plot of PK Concentration Over Time by Subject](./book/graphs/pharmacokinetic/pkcg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKCG02 -- Plot of PK Concentration Over Time by Cohort/Treatment Group/Dose](./book/graphs/pharmacokinetic/pkcg02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKCG03 -- Plot of Mean PK Concentration Over Time by Cohort](./book/graphs/pharmacokinetic/pkcg03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPG01 -- Plot of Mean Cumulative Percentage (%) of Recovered Drug in Urine](./book/graphs/pharmacokinetic/pkpg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPG02 -- Pharmacokinetic Parameter Summary of Serum PK Parameters by Treatment](./book/graphs/pharmacokinetic/pkpg02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPG03 -- Box Plot of Pharmacokinetic Parameters by Visit -- Plasma](./book/graphs/pharmacokinetic/pkpg03.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPG04 -- Box Plot of Pharmacokinetic Parameters by Visit -- Plasma](./book/graphs/pharmacokinetic/pkpg04.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[PKPG06 -- Boxplot of Metabolite to Parent Ratios by Treatment](./book/graphs/pharmacokinetic/pkpg06.qmd)


#### Other

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[BRG01 -- Bar Chart](./book/graphs/other/brg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[BWG01 -- Box Plot](./book/graphs/other/bwg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CIG01 -- Confidence Interval Plot](./book/graphs/other/cig01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[FSTG01 -- Subgroup Analysis of Best Overall Response](./book/graphs/other/fstg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[FSTG02 -- Subgroup Analysis of Survival Duration](./book/graphs/other/fstg02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[IPPG01 -- Individual Patient Plot Over Time](./book/graphs/other/ippg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[KMG01 -- Kaplan-Meier Plot](./book/graphs/other/kmg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[LTG01 -- Lattice Plot of Laboratory Tests by Treatment Group Over Time](./book/graphs/other/ltg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[MMRMG01 -- Plots for Mixed-Effect Model Repeated Measures Analysis](./book/graphs/other/mmrmg01.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[MMRMG02 -- Forest Plot for Mixed-Effect Model Repeated Measures](./book/graphs/other/mmrmg02.qmd)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[MNG01 -- Mean Plot](./book/graphs/other/mng01.qmd)

